### ISSUE TITLE
Error: Tag start is Not Closed

### ISSUE THREAD

**Issue by Faris-Ihsan** [Faris-Ihsan/CodeProyek2#2]

**Comment by syabrienapv** [comment]
Tag start is Not Closed

**Comment by Faris-Ihsan** [comment]
Masalah: ada tag yang tidak ada penutupnya 
` <TextView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_alignParentTop="true"
        android:layout_marginTop="18dp"
        android:textColor="#000000"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintRight_toRightOf="parent"
        app:layout_constraintTop_toTopOf="parent"
        android:text="@string/Tabungan_anda"  `

Soslusi: 
Menambahkan penutup "/>" pada akhir kode
`    <TextView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_alignParentTop="true"
        android:layout_marginTop="18dp"
        android:textColor="#000000"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintRight_toRightOf="parent"
        app:layout_constraintTop_toTopOf="parent"
        android:text="@string/Tabungan_anda" />`
