### ISSUE TITLE
Error: ; expected

### ISSUE THREAD

**Issue by syabrienapv** [Faris-Ihsan/CodeProyek2#48]

**Comment by Faris-Ihsan** [comment]
Error:

`public Cursor tampilkanDataKeluar() {
SQLiteDatabase db = this.getReadableDatabase();
Cursor res;
res = db.rawQuery("SELECT * FROM "+TBLNAME2,null);
return 
`

**Comment by Faris-Ihsan** [comment]
Solusi: 

`public Cursor tampilkanDataKeluar() { SQLiteDatabase db = this.getReadableDatabase(); Cursor res; res = db.rawQuery("SELECT * FROM "+TBLNAME2,null); return; `
